let questions=[{
    question:"vilken huvudstad  är av sverige?",
    answer:[{text:"malmö", correct:"false"},
            {text:"stockholm", correct:"true"},
            {text:"kamlar", correct:"false"},
            {text:"gavla", correct:"false"},
    ],
},
{
    question:"vilken huvudstad  är av italien?",
    answer:[{text:"roma", correct:"true"},
            {text:"milano", correct:"flase"},
            {text:"verona", correct:"false"},
            {text:"bergamo", correct:"false"},
    ],
},
{
    question:"vilken huvudstad  är av france?",
    answer:[{text:"nice", correct:"false"},
            {text:"marsellie", correct:"false"},
            {text:"paris", correct:"true"},
            {text:"lyon", correct:"false"},
    ],
},
{
    question:"vilken huvudstad  är av spain?",
    answer:[{text:"barcelona", correct:"false"},
            {text:"valencia", correct:"false"},
            {text:"malaga", correct:"false"},
            {text:"madrid", correct:"true"},
    ],
},
{
    question:"vilken huvudstad  är av usa?",
    answer:[{text:"washington", correct:"true"},
            {text:"newyork", correct:"false"},
            {text:"chicago", correct:"false"},
            {text:"san diego", correct:"false"},
    ],
},
{
    question:"vilken huvudstad  är av canada?",
    answer:[{text:"toronto", correct:"false"},
            {text:"ottawa", correct:"true"},
            {text:"quebec", correct:"false"},
            {text:"calgary", correct:"false"},
    ],
},
{
    question:"vilken huvudstad  är av austrialia?",
    answer:[{text:"melbourne", correct:"false"},
            {text:"perth", correct:"flase"},
            {text:"sydney", correct:"true"},
            {text:"adelaide", correct:"false"},
    ],
},
{
    question:"vilken huvudstad  är av egypt?",
    answer:[{text:"assiut", correct:"false"},
            {text:"alexandria", correct:"false"},
            {text:"sharm el shiek", correct:"false"},
            {text:"cairo", correct:"true"},
    ],
},
{
    question:"vilken huvudstad  är av tyskland?",
    answer:[{text:"berlin", correct:"true"},
            {text:"hamburg", correct:"false"},
            {text:"munchen", correct:"false"},
            {text:"dresden", correct:"false"},
],
},{
    question:"vilken huvudstad  är av uk?",
    answer:[{text:"liverpool", correct:"false"},
            {text:"london", correct:"true"},
            {text:"leicester", correct:"false"},
            {text:"manchester", correct:"false"},
    ],
}
]